Feature/view performance
gothub-team/got-client pull request #7
Opened 2022-06-15 12:00 UTC by Berndy

2022-06-15 16:39 UTC, AlphaBroke approved these changes
Nice 1

2022-06-19 12:20 UTC, vinnichase requested changes

2022-06-19 12:20 UTC, vinnichase commented on packages/got-util/src/index.js
> +export const mutAssocPath = (path, val) => input => {
assocPathMut or assocPathMutate

2022-06-19 12:20 UTC, vinnichase commented on packages/got-store/src/tests/views.spec.js
> +                for (let i = 0; i < 100; i += 1) {
Exclude to util as generate random graph

2022-06-19 14:50 UTC, vinnichase approved these changes

2022-07-21 11:09 UTC, andvrs approved these changes
Very nice job. Keep it up

2022-07-21 11:09 UTC, andvrs commented on packages/got-util/src/index.d.ts
> +/**
why 2

2022-07-21 11:09 UTC, merged